// 译林版小学英语单词表（自动从 Excel 生成，全 8 册，约 991 词）
const ALL_WORDS = [
  { en: "Hello", cn: "你好", book: "3A", unit: "1" },
  { en: "Good morning", cn: "早上好。", book: "3A", unit: "1" },
  { en: "Miss", cn: "小姐", book: "3A", unit: "1" },
  { en: "Hi.", cn: "你好。", book: "3A", unit: "1" },
  { en: "Good afternoon", cn: "下午好。", book: "3A", unit: "1" },
  { en: "class", cn: "同学们", book: "3A", unit: "1" },
  { en: "I", cn: "我", book: "3A", unit: "1" },
  { en: "I'm", cn: "(= I am) 我是", book: "3A", unit: "1" },
  { en: "are", cn: "是", book: "3A", unit: "2" },
  { en: "you", cn: "你", book: "3A", unit: "2" },
  { en: "yes", cn: "是；对", book: "3A", unit: "2" },
  { en: "am", cn: "是", book: "3A", unit: "2" },
  { en: "no", cn: "不；不是；没有", book: "3A", unit: "2" },
  { en: "not", cn: "不；没有", book: "3A", unit: "2" },
  { en: "Goodbye", cn: "再见。", book: "3A", unit: "2" },
  { en: "my", cn: "我的", book: "3A", unit: "3" },
  { en: "friend", cn: "朋友", book: "3A", unit: "3" },
  { en: "she", cn: "她", book: "3A", unit: "3" },
  { en: "she's", cn: "(=she is) 她是", book: "3A", unit: "3" },
  { en: "he", cn: "他", book: "3A", unit: "3" },
  { en: "he's", cn: "(=he is) 他是", book: "3A", unit: "3" },
  { en: "too", cn: "也", book: "3A", unit: "3" },
  { en: "this", cn: "这；这个", book: "3A", unit: "3" },
  { en: "is", cn: "是", book: "3A", unit: "3" },
  { en: "sister", cn: "姐姐；妹妹", book: "3A", unit: "3" },
  { en: "family", cn: "家；家庭", book: "3A", unit: "4" },
  { en: "father", cn: "父亲；爸爸", book: "3A", unit: "4" },
  { en: "mother", cn: "母亲；妈妈", book: "3A", unit: "4" },
  { en: "brother", cn: "哥哥；弟弟", book: "3A", unit: "4" },
  { en: "me", cn: "我", book: "3A", unit: "4" },
  { en: "grandpa", cn: "祖父；外祖父", book: "3A", unit: "4" },
  { en: "grandma", cn: "祖母；外祖母", book: "3A", unit: "4" },
  { en: "Good evening.", cn: "晚上好。", book: "3A", unit: "4" },
  { en: "look at", cn: "看；瞧", book: "3A", unit: "5" },
  { en: "T-shirt", cn: "T恤衫", book: "3A", unit: "5" },
  { en: "it", cn: "它", book: "3A", unit: "5" },
  { en: "it's", cn: "(= it is) 它是", book: "3A", unit: "5" },
  { en: "nice", cn: "好看的；好的", book: "3A", unit: "5" },
  { en: "skirt", cn: "裙子", book: "3A", unit: "5" },
  { en: "How nice!", cn: "真好看!", book: "3A", unit: "5" },
  { en: "cap", cn: "便帽；帽子", book: "3A", unit: "5" },
  { en: "great", cn: "好极了；很好", book: "3A", unit: "5" },
  { en: "jacket", cn: "夹克衫", book: "3A", unit: "5" },
  { en: "new", cn: "新的", book: "3A", unit: "5" },
  { en: "What colour ...?", cn: "……是什么颜色的?", book: "3A", unit: "5" },
  { en: "red", cn: "红色的", book: "3A", unit: "5" },
  { en: "colour", cn: "颜色", book: "3A", unit: "6" },
  { en: "orange", cn: "橙色的", book: "3A", unit: "6" },
  { en: "now", cn: "现在；目前", book: "3A", unit: "6" },
  { en: "green", cn: "绿色的", book: "3A", unit: "6" },
  { en: "and", cn: "和；与；又", book: "3A", unit: "6" },
  { en: "yellow", cn: "黄色的", book: "3A", unit: "6" },
  { en: "black", cn: "黑色的", book: "3A", unit: "6" },
  { en: "blue", cn: "蓝色的", book: "3A", unit: "6" },
  { en: "brown", cn: "棕色的", book: "3A", unit: "6" },
  { en: "white", cn: "白色的", book: "3A", unit: "6" },
  { en: "Would you like ...?", cn: "你想要......吗?", book: "3A", unit: "6" },
  { en: "an", cn: "一个", book: "3A", unit: "6" },
  { en: "Yes，please.", cn: "好的；太感谢了.。", book: "3A", unit: "6" },
  { en: "or", cn: "或；还是", book: "3A", unit: "6" },
  { en: "a", cn: "一个", book: "3A", unit: "7" },
  { en: "pie", cn: "馅饼；派", book: "3A", unit: "7" },
  { en: "Nice to meet you.", cn: "很高兴认识你。", book: "3A", unit: "7" },
  { en: "No，thank you.", cn: "不；谢谢你。", book: "3A", unit: "7" },
  { en: "What about ...?", cn: "……怎么样？", book: "3A", unit: "7" },
  { en: "cake", cn: "蛋糕；糕饼", book: "3A", unit: "7" },
  { en: "ice cream", cn: "冰淇淋", book: "3A", unit: "7" },
  { en: "sweet", cn: "糖果", book: "3A", unit: "7" },
  { en: "hot dog", cn: "热狗", book: "3A", unit: "7" },
  { en: "look", cn: "看；瞧", book: "3A", unit: "7" },
  { en: "what", cn: "什么", book: "3A", unit: "7" },
  { en: "what's", cn: "(=what is) 什么是", book: "3A", unit: "7" },
  { en: "Happy New Year!", cn: "新年快乐!", book: "3A", unit: "8" },
  { en: "uncle", cn: "叔父;伯父;舅父;姑父;姨夫", book: "3A", unit: "8" },
  { en: "This is for you.", cn: "这是给你的。", book: "3A", unit: "8" },
  { en: "doll", cn: "玩具娃娃", book: "3A", unit: "8" },
  { en: "that", cn: "那；那个", book: "3A", unit: "8" },
  { en: "ball", cn: "球", book: "3A", unit: "8" },
  { en: "robot", cn: "机器人", book: "3A", unit: "8" },
  { en: "CD", cn: "光盘", book: "3A", unit: "8" },
  { en: "car", cn: "小汽车；轿车", book: "3A", unit: "8" },
  { en: "Happy birthday!", cn: "生日快乐!", book: "3A", unit: "8" },
  { en: "toy", cn: "玩具", book: "3A", unit: "8" },
  { en: "ah", cn: "啊", book: "3A", unit: "8" },
  { en: "ha", cn: "哈", book: "3A", unit: "8" },
  { en: "in class", cn: "在上课", book: "3B", unit: "1" },
  { en: "Stand up.", cn: "起立", book: "3B", unit: "1" },
  { en: "Mr", cn: "先生", book: "3B", unit: "1" },
  { en: "sit down.", cn: "坐下", book: "3B", unit: "1" },
  { en: "please", cn: "请", book: "3B", unit: "1" },
  { en: "open", cn: "开；打开", book: "3B", unit: "1" },
  { en: "the", cn: "这个；这些；那个；那些", book: "3B", unit: "1" },
  { en: "door", cn: "门", book: "3B", unit: "1" },
  { en: "sorry", cn: "对不起", book: "3B", unit: "1" },
  { en: "come in", cn: "进来", book: "3B", unit: "1" },
  { en: "close", cn: "关上；合上", book: "3B", unit: "1" },
  { en: "window", cn: "窗; 窗户", book: "3B", unit: "1" },
  { en: "blackboard", cn: "黑板", book: "3B", unit: "1" },
  { en: "book", cn: "书", book: "3B", unit: "1" },
  { en: "rubber", cn: "橡皮", book: "3B", unit: "1" },
  { en: "don't", cn: "(= do not) 不要", book: "3B", unit: "1" },
  { en: "listen to", cn: "听", book: "3B", unit: "1" },
  { en: "parrot", cn: "鹦鹉", book: "3B", unit: "1" },
  { en: "in", cn: "在……里面", book: "3B", unit: "2" },
  { en: "library", cn: "图书馆", book: "3B", unit: "2" },
  { en: "shh", cn: "嘘", book: "3B", unit: "2" },
  { en: "shout", cn: "喊；叫", book: "3B", unit: "2" },
  { en: "run", cn: "跑，跑步", book: "3B", unit: "2" },
  { en: "eat", cn: "吃", book: "3B", unit: "2" },
  { en: "here", cn: "这里；在这里", book: "3B", unit: "2" },
  { en: "talk", cn: "说话；谈话", book: "3B", unit: "2" },
  { en: "sleep", cn: "睡觉", book: "3B", unit: "2" },
  { en: "drink", cn: "喝", book: "3B", unit: "2" },
  { en: "milk", cn: "牛奶", book: "3B", unit: "2" },
  { en: "English", cn: "英语", book: "3B", unit: "2" },
  { en: "your", cn: "你的；你们的", book: "3B", unit: "2" },
  { en: "pencil", cn: "铅笔", book: "3B", unit: "3" },
  { en: "isn't", cn: "(=is not) 是不是", book: "3B", unit: "3" },
  { en: "that's", cn: "(=that is) 那是", book: "3B", unit: "3" },
  { en: "schoolbag", cn: "书包", book: "3B", unit: "3" },
  { en: "pen", cn: "钢笔", book: "3B", unit: "3" },
  { en: "crayon", cn: "蜡笔", book: "3B", unit: "3" },
  { en: "ruler", cn: "尺子", book: "3B", unit: "3" },
  { en: "pencil case", cn: "铅笔盒；铅笔袋", book: "3B", unit: "3" },
  { en: "lunch box", cn: "午餐盒", book: "3B", unit: "3" },
  { en: "where", cn: "在哪里", book: "3B", unit: "3" },
  { en: "where's", cn: "(=where is) 在哪里", book: "3B", unit: "3" },
  { en: "over there", cn: "在那里", book: "3B", unit: "3" },
  { en: "bird", cn: "鸟", book: "3B", unit: "4" },
  { en: "beautiful", cn: "漂亮的；美丽的", book: "3B", unit: "4" },
  { en: "under", cn: "在……下面", book: "3B", unit: "4" },
  { en: "desk", cn: "课桌；书桌", book: "3B", unit: "4" },
  { en: "behind", cn: "在……后面", book: "3B", unit: "4" },
  { en: "on", cn: "在……上面", book: "3B", unit: "4" },
  { en: "chair", cn: "椅子", book: "3B", unit: "4" },
  { en: "tree", cn: "树", book: "3B", unit: "4" },
  { en: "guess", cn: "猜；猜测", book: "3B", unit: "4" },
  { en: "one", cn: "一", book: "3B", unit: "4" },
  { en: "two", cn: "二", book: "3B", unit: "4" },
  { en: "three", cn: "三", book: "3B", unit: "4" },
  { en: "oh", cn: "哦；啊", book: "3B", unit: "4" },
  { en: "wow", cn: "哇,呀", book: "3B", unit: "4" },
  { en: "How old are you?", cn: "你多大了？", book: "3B", unit: "5" },
  { en: "lovely", cn: "可爱的", book: "3B", unit: "5" },
  { en: "nine", cn: "九", book: "3B", unit: "5" },
  { en: "eight", cn: "八", book: "3B", unit: "5" },
  { en: "four", cn: "四", book: "3B", unit: "5" },
  { en: "five", cn: "五", book: "3B", unit: "5" },
  { en: "six", cn: "六", book: "3B", unit: "5" },
  { en: "seven", cn: "七", book: "3B", unit: "5" },
  { en: "ten", cn: "十", book: "3B", unit: "5" },
  { en: "right", cn: "对的；正确的", book: "3B", unit: "5" },
  { en: "out", cn: "出", book: "3B", unit: "5" },
  { en: "What a nice cake!", cn: "多么好的蛋糕！", book: "3B", unit: "5" },
  { en: "make a wish", cn: "许个愿", book: "3B", unit: "5" },
  { en: "want", cn: "希望", book: "3B", unit: "5" },
  { en: "It's time for ...", cn: "是时候了…", book: "3B", unit: "5" },
  { en: "What time is it?", cn: "几点了？", book: "3B", unit: "6" },
  { en: "wake up", cn: "醒；醒来", book: "3B", unit: "6" },
  { en: "mum", cn: "妈妈", book: "3B", unit: "6" },
  { en: "o'clock", cn: "……点钟", book: "3B", unit: "6" },
  { en: "breakfast", cn: "早餐；早饭", book: "3B", unit: "6" },
  { en: "hurry up", cn: "快点", book: "3B", unit: "6" },
  { en: "class", cn: "课；上课", book: "3B", unit: "6" },
  { en: "dinner", cn: "晚餐；晚饭", book: "3B", unit: "6" },
  { en: "bed", cn: "床", book: "3B", unit: "6" },
  { en: "OK", cn: "好；行", book: "3B", unit: "6" },
  { en: "lunch", cn: "午餐；午饭", book: "3B", unit: "6" },
  { en: "eleven", cn: "十一", book: "3B", unit: "6" },
  { en: "twelve", cn: "十二", book: "3B", unit: "6" },
  { en: "bag", cn: "包；书包", book: "3B", unit: "6" },
  { en: "these", cn: "这些", book: "3B", unit: "6" },
  { en: "here's", cn: "(=here is) 这是", book: "3B", unit: "6" },
  { en: "farm", cn: "农场", book: "3B", unit: "7" },
  { en: "Welcome to ...", cn: "欢迎来到……", book: "3B", unit: "7" },
  { en: "they", cn: "他们；她们；它们", book: "3B", unit: "7" },
  { en: "they're", cn: "(= they are) 他们是", book: "3B", unit: "7" },
  { en: "pig", cn: "猪", book: "3B", unit: "7" },
  { en: "those", cn: "那些", book: "3B", unit: "7" },
  { en: "cow", cn: "奶牛", book: "3B", unit: "7" },
  { en: "apple", cn: "苹果", book: "3B", unit: "7" },
  { en: "pear", cn: "梨", book: "3B", unit: "7" },
  { en: "chicken", cn: "鸡", book: "3B", unit: "7" },
  { en: "duck", cn: "鸭子", book: "3B", unit: "7" },
  { en: "orange", cn: "橙子", book: "3B", unit: "7" },
  { en: "picture", cn: "图画;照片", book: "3B", unit: "7" },
  { en: "who", cn: "谁", book: "3B", unit: "7" },
  { en: "who's", cn: "(= who is) 谁的", book: "3B", unit: "7" },
  { en: "we", cn: "我们", book: "3B", unit: "8" },
  { en: "we're", cn: "(= we are) 我们是", book: "3B", unit: "8" },
  { en: "twin", cn: "双胞胎之一", book: "3B", unit: "8" },
  { en: "aunt", cn: "姨母；伯母；婶母；舅母", book: "3B", unit: "8" },
  { en: "girl", cn: "女孩", book: "3B", unit: "8" },
  { en: "man", cn: "男人；人", book: "3B", unit: "8" },
  { en: "woman", cn: "妇女；女人", book: "3B", unit: "8" },
  { en: "boy", cn: "男孩", book: "3B", unit: "8" },
  { en: "baby", cn: "婴儿；宝宝", book: "3B", unit: "8" },
  { en: "cousin", cn: "堂兄弟(姐妹)表兄弟(姐妹)", book: "3B", unit: "8" },
  { en: "name", cn: "名字", book: "3B", unit: "8" },
  { en: "like", cn: "喜欢", book: "4A", unit: "1" },
  { en: "dog", cn: "狗", book: "4A", unit: "1" },
  { en: "animal", cn: "动物", book: "4A", unit: "1" },
  { en: "cat", cn: "猫", book: "4A", unit: "1" },
  { en: "cute", cn: "可爱的", book: "4A", unit: "1" },
  { en: "panda", cn: "熊猫", book: "4A", unit: "1" },
  { en: "fat", cn: "胖的", book: "4A", unit: "1" },
  { en: "elephant", cn: "大象", book: "4A", unit: "1" },
  { en: "horse", cn: "马", book: "4A", unit: "1" },
  { en: "lion", cn: "狮子", book: "4A", unit: "1" },
  { en: "monkey", cn: "猴子", book: "4A", unit: "1" },
  { en: "tiger", cn: "老虎", book: "4A", unit: "1" },
  { en: "have", cn: "有", book: "4A", unit: "1" },
  { en: "Let's ...", cn: "让咱们……", book: "4A", unit: "2" },
  { en: "let's", cn: "(= let us) 让我们", book: "4A", unit: "2" },
  { en: "make", cn: "做；制作", book: "4A", unit: "2" },
  { en: "fruit", cn: "水果", book: "4A", unit: "2" },
  { en: "salad", cn: "色拉", book: "4A", unit: "2" },
  { en: "pineapple", cn: "菠萝", book: "4A", unit: "2" },
  { en: "mango", cn: "芒果", book: "4A", unit: "2" },
  { en: "any", cn: "一些；任何的", book: "4A", unit: "2" },
  { en: "banana", cn: "香蕉", book: "4A", unit: "2" },
  { en: "some", cn: "一些", book: "4A", unit: "2" },
  { en: "grape", cn: "葡萄", book: "4A", unit: "2" },
  { en: "Thanks.", cn: "谢谢", book: "4A", unit: "2" },
  { en: "our", cn: "我们的", book: "4A", unit: "2" },
  { en: "cool", cn: "酷；真棒", book: "4A", unit: "2" },
  { en: "wonderful", cn: "精彩的；绝妙的", book: "4A", unit: "2" },
  { en: "how many", cn: "多少", book: "4A", unit: "2" },
  { en: "thirteen", cn: "十三", book: "4A", unit: "3" },
  { en: "sticker", cn: "贴纸", book: "4A", unit: "3" },
  { en: "can", cn: "可以；能；会", book: "4A", unit: "3" },
  { en: "have a look", cn: "看一看", book: "4A", unit: "3" },
  { en: "very", cn: "很，非常", book: "4A", unit: "3" },
  { en: "fifteen", cn: "十五", book: "4A", unit: "3" },
  { en: "sure", cn: "当然", book: "4A", unit: "3" },
  { en: "fourteen", cn: "十四", book: "4A", unit: "3" },
  { en: "sixteen", cn: "十六", book: "4A", unit: "3" },
  { en: "seventeen", cn: "十七", book: "4A", unit: "3" },
  { en: "eighteen", cn: "十八", book: "4A", unit: "3" },
  { en: "nineteen", cn: "十九", book: "4A", unit: "3" },
  { en: "play", cn: "玩；打（球）", book: "4A", unit: "3" },
  { en: "many", cn: "许多", book: "4A", unit: "3" },
  { en: "box", cn: "盒子", book: "4A", unit: "3" },
  { en: "table tennis", cn: "乒乓球", book: "4A", unit: "3" },
  { en: "but", cn: "但是", book: "4A", unit: "3" },
  { en: "do", cn: "做；干", book: "4A", unit: "3" },
  { en: "basketball", cn: "篮球", book: "4A", unit: "4" },
  { en: "well", cn: "好", book: "4A", unit: "4" },
  { en: "can't", cn: "(= can not) 不能", book: "4A", unit: "4" },
  { en: "have a try", cn: "试一试", book: "4A", unit: "4" },
  { en: "yeah", cn: "是的；对的", book: "4A", unit: "4" },
  { en: "football", cn: "足球", book: "4A", unit: "4" },
  { en: "jump", cn: "跳", book: "4A", unit: "4" },
  { en: "skate", cn: "溜冰；滑冰", book: "4A", unit: "4" },
  { en: "swim", cn: "游泳", book: "4A", unit: "4" },
  { en: "quack", cn: "（鸭子的）呱呱声", book: "4A", unit: "4" },
  { en: "tweet", cn: "（小鸟的）叽喳声", book: "4A", unit: "4" },
  { en: "fly", cn: "飞", book: "4A", unit: "4" },
  { en: "ouch", cn: "哎哟", book: "4A", unit: "4" },
  { en: "sad", cn: "难过的；伤心地", book: "4A", unit: "4" },
  { en: "either", cn: "也", book: "4A", unit: "4" },
  { en: "home", cn: "家", book: "4A", unit: "5" },
  { en: "bedroom", cn: "卧室", book: "4A", unit: "5" },
  { en: "living room", cn: "客厅", book: "4A", unit: "5" },
  { en: "sofa", cn: "沙发", book: "4A", unit: "5" },
  { en: "come", cn: "来", book: "4A", unit: "5" },
  { en: "kitchen", cn: "厨房", book: "4A", unit: "5" },
  { en: "clock", cn: "钟", book: "4A", unit: "5" },
  { en: "fridge", cn: "冰箱", book: "4A", unit: "5" },
  { en: "table", cn: "桌子", book: "4A", unit: "5" },
  { en: "bathroom", cn: "卫生间", book: "4A", unit: "5" },
  { en: "How are you?", cn: "你好吗?", book: "4A", unit: "5" },
  { en: "hungry", cn: "饿的；饥饿的", book: "4A", unit: "5" },
  { en: "What would you like?", cn: "你想要什么?", book: "4A", unit: "5" },
  { en: "I'd like...", cn: "我想要……", book: "4A", unit: "5" },
  { en: "at", cn: "在（某处）", book: "4A", unit: "6" },
  { en: "snack bar", cn: "快餐店；小吃店", book: "4A", unit: "6" },
  { en: "hamburger", cn: "汉堡包", book: "4A", unit: "6" },
  { en: "a glass of", cn: "一杯", book: "4A", unit: "6" },
  { en: "noodles", cn: "面条", book: "4A", unit: "6" },
  { en: "dad", cn: "爸爸", book: "4A", unit: "6" },
  { en: "sandwich", cn: "三明治", book: "4A", unit: "6" },
  { en: "a cup of", cn: "一杯", book: "4A", unit: "6" },
  { en: "coffee", cn: "咖啡", book: "4A", unit: "6" },
  { en: "Anything else", cn: "还要其他东西吗", book: "4A", unit: "6" },
  { en: "tea", cn: "茶", book: "4A", unit: "6" },
  { en: "juice", cn: "果汁", book: "4A", unit: "6" },
  { en: "rice", cn: "米饭；大米", book: "4A", unit: "6" },
  { en: "Me too", cn: "我也是", book: "4A", unit: "6" },
  { en: "fish", cn: "鱼", book: "4A", unit: "6" },
  { en: "Can I help you?", cn: "我能帮助你吗?", book: "4A", unit: "6" },
  { en: "big", cn: "大的", book: "4A", unit: "6" },
  { en: "how much", cn: "多少钱", book: "4A", unit: "7" },
  { en: "shoe", cn: "鞋子", book: "4A", unit: "7" },
  { en: "yuan", cn: "元（人民币）", book: "4A", unit: "7" },
  { en: "sock", cn: "袜子", book: "4A", unit: "7" },
  { en: "umbrella", cn: "伞", book: "4A", unit: "7" },
  { en: "only", cn: "只有；仅仅", book: "4A", unit: "7" },
  { en: "twenty-eight", cn: "二十八", book: "4A", unit: "7" },
  { en: "Well done.", cn: "好样的。干得好", book: "4A", unit: "7" },
  { en: "fan", cn: "扇子", book: "4A", unit: "7" },
  { en: "twenty", cn: "二十", book: "4A", unit: "7" },
  { en: "thirty", cn: "三十", book: "4A", unit: "7" },
  { en: "forty", cn: "四十", book: "4A", unit: "7" },
  { en: "fifty", cn: "五十", book: "4A", unit: "7" },
  { en: "forty-five", cn: "四十五", book: "4A", unit: "7" },
  { en: "her", cn: "她的", book: "4A", unit: "7" },
  { en: "tail", cn: "尾巴", book: "4A", unit: "7" },
  { en: "long", cn: "长的", book: "4A", unit: "7" },
  { en: "hair", cn: "头发", book: "4A", unit: "8" },
  { en: "eye", cn: "眼睛", book: "4A", unit: "8" },
  { en: "nose", cn: "鼻子", book: "4A", unit: "8" },
  { en: "mouth", cn: "嘴巴", book: "4A", unit: "8" },
  { en: "small", cn: "小的", book: "4A", unit: "8" },
  { en: "his", cn: "他的", book: "4A", unit: "8" },
  { en: "short", cn: "短的；矮的", book: "4A", unit: "8" },
  { en: "ear", cn: "耳朵", book: "4A", unit: "8" },
  { en: "king", cn: "国王", book: "4A", unit: "8" },
  { en: "thin", cn: "瘦的", book: "4A", unit: "8" },
  { en: "tall", cn: "高的", book: "4A", unit: "8" },
  { en: "snowman", cn: "雪人", book: "4A", unit: "8" },
  { en: "school", cn: "学校", book: "4B", unit: "1" },
  { en: "subject", cn: "课程", book: "4B", unit: "1" },
  { en: "Welcome back to ...", cn: "欢迎回到……", book: "4B", unit: "1" },
  { en: "see", cn: "看见，看到", book: "4B", unit: "1" },
  { en: "timetable", cn: "课程表；时间表", book: "4B", unit: "1" },
  { en: "Chinese", cn: "语文（课）", book: "4B", unit: "1" },
  { en: "maths", cn: "数学（课）", book: "4B", unit: "1" },
  { en: "art", cn: "美术（课）", book: "4B", unit: "1" },
  { en: "PE", cn: "体育（课）", book: "4B", unit: "1" },
  { en: "music", cn: "音乐（课）", book: "4B", unit: "1" },
  { en: "science", cn: "科学（课）", book: "4B", unit: "1" },
  { en: "fun", cn: "乐趣，快乐", book: "4B", unit: "1" },
  { en: "go to", cn: "去……", book: "4B", unit: "1" },
  { en: "playground", cn: "操场", book: "4B", unit: "1" },
  { en: "lesson", cn: "课", book: "4B", unit: "1" },
  { en: "Monday", cn: "星期一", book: "4B", unit: "1" },
  { en: "afternoon", cn: "下午", book: "4B", unit: "1" },
  { en: "after school", cn: "放学后", book: "4B", unit: "2" },
  { en: "go", cn: "去", book: "4B", unit: "2" },
  { en: "What day is it today?", cn: "今天星期几？", book: "4B", unit: "2" },
  { en: "Wednesday", cn: "星期三", book: "4B", unit: "2" },
  { en: "match", cn: "比赛", book: "4B", unit: "2" },
  { en: "today", cn: "今天", book: "4B", unit: "2" },
  { en: "What a pity!", cn: "真遗憾", book: "4B", unit: "2" },
  { en: "Saturday", cn: "星期六", book: "4B", unit: "2" },
  { en: "All right.", cn: "好的。", book: "4B", unit: "2" },
  { en: "Sunday", cn: "星期日", book: "4B", unit: "2" },
  { en: "Tuesday", cn: "星期二", book: "4B", unit: "2" },
  { en: "Thursday", cn: "星期四", book: "4B", unit: "2" },
  { en: "Friday", cn: "星期五", book: "4B", unit: "2" },
  { en: "get up", cn: "起床", book: "4B", unit: "2" },
  { en: "when", cn: "什么时候", book: "4B", unit: "2" },
  { en: "every", cn: "每个", book: "4B", unit: "2" },
  { en: "day", cn: "天", book: "4B", unit: "2" },
  { en: "usually", cn: "通常，常常", book: "4B", unit: "3" },
  { en: "go to school", cn: "上学", book: "4B", unit: "3" },
  { en: "in the morning", cn: "在上午", book: "4B", unit: "3" },
  { en: "have lunch", cn: "吃午饭", book: "4B", unit: "3" },
  { en: "in the afternoon", cn: "在下午", book: "4B", unit: "3" },
  { en: "play football", cn: "踢足球", book: "4B", unit: "3" },
  { en: "go home", cn: "回家", book: "4B", unit: "3" },
  { en: "homework", cn: "家庭作业", book: "4B", unit: "3" },
  { en: "have dinner", cn: "吃晚饭", book: "4B", unit: "3" },
  { en: "watch TV", cn: "看电视", book: "4B", unit: "3" },
  { en: "go to bed", cn: "睡觉", book: "4B", unit: "3" },
  { en: "in the evening", cn: "在晚上", book: "4B", unit: "3" },
  { en: "at night", cn: "在夜里", book: "4B", unit: "3" },
  { en: "drawing", cn: "画画", book: "4B", unit: "4" },
  { en: "park", cn: "公园", book: "4B", unit: "4" },
  { en: "draw", cn: "画", book: "4B", unit: "4" },
  { en: "Good ideal!", cn: "好主意！", book: "4B", unit: "4" },
  { en: "flower", cn: "花，花朵", book: "4B", unit: "4" },
  { en: "them", cn: "他们；她们；它们", book: "4B", unit: "4" },
  { en: "easy", cn: "容易的，简单的", book: "4B", unit: "4" },
  { en: "boat", cn: "小船", book: "4B", unit: "4" },
  { en: "river", cn: "河；江", book: "4B", unit: "4" },
  { en: "difficult", cn: "难的，困难的", book: "4B", unit: "4" },
  { en: "try", cn: "试", book: "4B", unit: "4" },
  { en: "hill", cn: "小山，山丘", book: "4B", unit: "4" },
  { en: "lake", cn: "湖，湖泊", book: "4B", unit: "4" },
  { en: "again", cn: "再一次，又一次", book: "4B", unit: "4" },
  { en: "season", cn: "季节", book: "4B", unit: "5" },
  { en: "spring", cn: "春天，春季", book: "4B", unit: "5" },
  { en: "warm", cn: "温暖的，温和的", book: "4B", unit: "5" },
  { en: "fly", cn: "放（风筝、飞机模型等）", book: "4B", unit: "5" },
  { en: "kite", cn: "风筝", book: "4B", unit: "5" },
  { en: "go boating", cn: "去划船", book: "4B", unit: "5" },
  { en: "summer", cn: "夏天，夏季", book: "4B", unit: "5" },
  { en: "hot", cn: "热的，炎热的", book: "4B", unit: "5" },
  { en: "go swimming", cn: "去游泳", book: "4B", unit: "5" },
  { en: "autumn", cn: "秋天，秋季", book: "4B", unit: "5" },
  { en: "cool", cn: "凉爽的，凉快的", book: "4B", unit: "5" },
  { en: "picnic", cn: "野餐", book: "4B", unit: "5" },
  { en: "go climbing", cn: "去爬山", book: "4B", unit: "5" },
  { en: "winter", cn: "冬天，冬季", book: "4B", unit: "5" },
  { en: "cold", cn: "冷的，寒冷的", book: "4B", unit: "5" },
  { en: "go skating", cn: "去溜冰；去滑冰", book: "4B", unit: "5" },
  { en: "fine", cn: "晴朗的", book: "4B", unit: "5" },
  { en: "hey", cn: "嘿，喂", book: "4B", unit: "5" },
  { en: "whose", cn: "谁的", book: "4B", unit: "5" },
  { en: "dress", cn: "连衣裙", book: "4B", unit: "6" },
  { en: "too", cn: "太，过于", book: "4B", unit: "6" },
  { en: "trousers", cn: "裤子", book: "4B", unit: "6" },
  { en: "party", cn: "聚会，派对", book: "4B", unit: "6" },
  { en: "glove", cn: "手套", book: "4B", unit: "6" },
  { en: "so", cn: "如此，这么", book: "4B", unit: "6" },
  { en: "coat", cn: "外衣，外套", book: "4B", unit: "6" },
  { en: "shirt", cn: "（男式）衬衫", book: "4B", unit: "6" },
  { en: "sweater", cn: "毛衣；绒衣", book: "4B", unit: "6" },
  { en: "jeans", cn: "牛仔裤", book: "4B", unit: "6" },
  { en: "shorts", cn: "短裤", book: "4B", unit: "6" },
  { en: "wrong", cn: "错的，错误的", book: "4B", unit: "6" },
  { en: "move", cn: "移动", book: "4B", unit: "6" },
  { en: "I thingk so.", cn: "我想是。", book: "4B", unit: "6" },
  { en: "What's the matter?", cn: "怎么了？", book: "4B", unit: "6" },
  { en: "hand", cn: "手", book: "4B", unit: "6" },
  { en: "hurt", cn: "感到疼痛", book: "4B", unit: "6" },
  { en: "thirsty", cn: "渴的，口渴的", book: "4B", unit: "7" },
  { en: "water", cn: "水", book: "4B", unit: "7" },
  { en: "ill", cn: "生病的", book: "4B", unit: "7" },
  { en: "tired", cn: "累的，疲劳的", book: "4B", unit: "7" },
  { en: "Good night.", cn: "晚安。", book: "4B", unit: "7" },
  { en: "dear", cn: "亲爱的", book: "4B", unit: "7" },
  { en: "happy", cn: "快乐的，高兴的", book: "4B", unit: "7" },
  { en: "Mrs", cn: "夫人，太太", book: "4B", unit: "7" },
  { en: "speak", cn: "说话，讲话", book: "4B", unit: "7" },
  { en: "may", cn: "可以", book: "4B", unit: "8" },
  { en: "come to school", cn: "来学校", book: "4B", unit: "8" },
  { en: "cold", cn: "感冒", book: "4B", unit: "8" },
  { en: "fever", cn: "发烧", book: "4B", unit: "8" },
  { en: "hear", cn: "听到，听见", book: "4B", unit: "8" },
  { en: "take care", cn: "保重", book: "4B", unit: "8" },
  { en: "I'm fine,thank you.", cn: "我很好，谢谢。", book: "4B", unit: "8" },
  { en: "See you tomorrow.", cn: "明天见。", book: "4B", unit: "8" },
  { en: "See you.", cn: "再见。", book: "4B", unit: "8" },
  { en: "cough", cn: "咳嗽", book: "4B", unit: "8" },
  { en: "headache", cn: "头疼，头痛", book: "4B", unit: "8" },
  { en: "Not so good.", cn: "不太好。", book: "4B", unit: "8" },
  { en: "at school", cn: "在上学；在学校", book: "4B", unit: "8" },
  { en: "bear", cn: "熊", book: "5A", unit: "1" },
  { en: "forest", cn: "森林", book: "5A", unit: "1" },
  { en: "there", cn: "（与be连用）有", book: "5A", unit: "1" },
  { en: "house", cn: "房子", book: "5A", unit: "1" },
  { en: "soup", cn: "汤", book: "5A", unit: "1" },
  { en: "just right", cn: "正合适，正好", book: "5A", unit: "1" },
  { en: "room", cn: "房间", book: "5A", unit: "1" },
  { en: "hard", cn: "硬的", book: "5A", unit: "1" },
  { en: "soft", cn: "柔软的", book: "5A", unit: "1" },
  { en: "afraid", cn: "害怕的", book: "5A", unit: "1" },
  { en: "in front of", cn: "在...前面", book: "5A", unit: "1" },
  { en: "her", cn: "她", book: "5A", unit: "1" },
  { en: "Help!", cn: "救命啊！", book: "5A", unit: "1" },
  { en: "beside", cn: "在...旁边", book: "5A", unit: "1" },
  { en: "between", cn: "在...中间", book: "5A", unit: "1" },
  { en: "really", cn: "真的", book: "5A", unit: "1" },
  { en: "then", cn: "然后", book: "5A", unit: "1" },
  { en: "find", cn: "找到，发现", book: "5A", unit: "1" },
  { en: "their", cn: "他们的；她们的；它们的", book: "5A", unit: "1" },
  { en: "student", cn: "学生", book: "5A", unit: "2" },
  { en: "show ... around", cn: "带...参观", book: "5A", unit: "2" },
  { en: "classroom", cn: "教室", book: "5A", unit: "2" },
  { en: "second", cn: "第二", book: "5A", unit: "2" },
  { en: "floor", cn: "楼层", book: "5A", unit: "2" },
  { en: "computer", cn: "电脑", book: "5A", unit: "2" },
  { en: "third", cn: "第三", book: "5A", unit: "2" },
  { en: "first", cn: "第一；首先", book: "5A", unit: "2" },
  { en: "swing", cn: "秋千", book: "5A", unit: "2" },
  { en: "push", cn: "推", book: "5A", unit: "2" },
  { en: "heavy", cn: "重的，沉的", book: "5A", unit: "2" },
  { en: "stop", cn: "停下，停止", book: "5A", unit: "2" },
  { en: "high", cn: "高的", book: "5A", unit: "2" },
  { en: "great", cn: "很多的，极大的", book: "5A", unit: "2" },
  { en: "one ... ,the other ...", cn: "一个......，另一个......", book: "5A", unit: "3" },
  { en: "body", cn: "身体", book: "5A", unit: "3" },
  { en: "no", cn: "没有，无", book: "5A", unit: "3" },
  { en: "leg", cn: "腿", book: "5A", unit: "3" },
  { en: "or", cn: "也不，也没有", book: "5A", unit: "3" },
  { en: "arm", cn: "手臂", book: "5A", unit: "3" },
  { en: "wing", cn: "翅膀", book: "5A", unit: "3" },
  { en: "foot", cn: "脚，足", book: "5A", unit: "3" },
  { en: "rabbit", cn: "兔子", book: "5A", unit: "3" },
  { en: "give", cn: "给", book: "5A", unit: "3" },
  { en: "finger", cn: "手指", book: "5A", unit: "3" },
  { en: "hobby", cn: "业余爱好", book: "5A", unit: "4" },
  { en: "be good at", cn: "擅长于", book: "5A", unit: "4" },
  { en: "with", cn: "与......一起", book: "5A", unit: "4" },
  { en: "also", cn: "也", book: "5A", unit: "4" },
  { en: "read", cn: "读，阅读", book: "5A", unit: "4" },
  { en: "story", cn: "故事", book: "5A", unit: "4" },
  { en: "a lot of", cn: "很多", book: "5A", unit: "4" },
  { en: "play the piano", cn: "弹钢琴", book: "5A", unit: "4" },
  { en: "dance", cn: "跳舞", book: "5A", unit: "4" },
  { en: "watch films", cn: "看电影", book: "5A", unit: "4" },
  { en: "both", cn: "两个都", book: "5A", unit: "4" },
  { en: "sing", cn: "唱歌", book: "5A", unit: "4" },
  { en: "group", cn: "组", book: "5A", unit: "4" },
  { en: "about", cn: "关于", book: "5A", unit: "4" },
  { en: "idea", cn: "主意", book: "5A", unit: "4" },
  { en: "ice", cn: "冰", book: "5A", unit: "4" },
  { en: "hole", cn: "洞", book: "5A", unit: "4" },
  { en: "Look out!", cn: "当心！注意！", book: "5A", unit: "4" },
  { en: "wet", cn: "湿的，潮的", book: "5A", unit: "4" },
  { en: "teacher", cn: "老师", book: "5A", unit: "5" },
  { en: "teach", cn: "教", book: "5A", unit: "5" },
  { en: "writer", cn: "作家", book: "5A", unit: "5" },
  { en: "write", cn: "写", book: "5A", unit: "5" },
  { en: "work", cn: "工作", book: "5A", unit: "5" },
  { en: "at home", cn: "在家", book: "5A", unit: "5" },
  { en: "doctor", cn: "医生", book: "5A", unit: "5" },
  { en: "help", cn: "帮助", book: "5A", unit: "5" },
  { en: "sick", cn: "生病的", book: "5A", unit: "5" },
  { en: "people", cn: "人；人们", book: "5A", unit: "5" },
  { en: "factory", cn: "工厂", book: "5A", unit: "5" },
  { en: "worker", cn: "工人", book: "5A", unit: "5" },
  { en: "cook", cn: "厨师", book: "5A", unit: "5" },
  { en: "driver", cn: "驾驶员，司机", book: "5A", unit: "5" },
  { en: "farmer", cn: "农民", book: "5A", unit: "5" },
  { en: "nurse", cn: "护士", book: "5A", unit: "5" },
  { en: "policeman", cn: "警察", book: "5A", unit: "5" },
  { en: "e-friend", cn: "网友", book: "5A", unit: "6" },
  { en: "Wait a minute.", cn: "等一会儿", book: "5A", unit: "6" },
  { en: "send", cn: "发出（信件、邮件等）", book: "5A", unit: "6" },
  { en: "to", cn: "给", book: "5A", unit: "6" },
  { en: "live", cn: "住，居住", book: "5A", unit: "6" },
  { en: "UK", cn: "英国", book: "5A", unit: "6" },
  { en: "... years old", cn: "……岁", book: "5A", unit: "6" },
  { en: "Australia", cn: "澳大利亚", book: "5A", unit: "6" },
  { en: "Canada", cn: "加拿大", book: "5A", unit: "6" },
  { en: "China", cn: "中国", book: "5A", unit: "6" },
  { en: "US", cn: "美国", book: "5A", unit: "6" },
  { en: "go fishing", cn: "去钓鱼", book: "5A", unit: "6" },
  { en: "tomorrow", cn: "明天", book: "5A", unit: "6" },
  { en: "fishing", cn: "钓鱼，捕鱼", book: "5A", unit: "6" },
  { en: "Don't worry", cn: "别担心", book: "5A", unit: "6" },
  { en: "sit", cn: "坐，坐在", book: "5A", unit: "6" },
  { en: "by ...", cn: "在……旁边", book: "5A", unit: "6" },
  { en: "wait", cn: "等，等待", book: "5A", unit: "6" },
  { en: "at weekends", cn: "在周末", book: "5A", unit: "7" },
  { en: "visit", cn: "拜访；参观", book: "5A", unit: "7" },
  { en: "grandparent", cn: "祖父;祖母;外祖父;外祖母", book: "5A", unit: "7" },
  { en: "play with", cn: "和......一起玩", book: "5A", unit: "7" },
  { en: "very much", cn: "非常", book: "5A", unit: "7" },
  { en: "often", cn: "经常，常常", book: "5A", unit: "7" },
  { en: "chat", cn: "聊天", book: "5A", unit: "7" },
  { en: "Internet", cn: "网络；互联网", book: "5A", unit: "7" },
  { en: "always", cn: "总是；一直", book: "5A", unit: "7" },
  { en: "sometimes", cn: "有时", book: "5A", unit: "7" },
  { en: "go to the cinema", cn: "去看电影", book: "5A", unit: "7" },
  { en: "there", cn: "那里", book: "5A", unit: "7" },
  { en: "a lot", cn: "很多", book: "5A", unit: "7" },
  { en: "come out", cn: "出来", book: "5A", unit: "7" },
  { en: "get out", cn: "出来", book: "5A", unit: "7" },
  { en: "Christmas", cn: "圣诞节", book: "5A", unit: "8" },
  { en: "buy", cn: "买", book: "5A", unit: "8" },
  { en: "present", cn: "礼物", book: "5A", unit: "8" },
  { en: "Christmas tree", cn: "圣诞树", book: "5A", unit: "8" },
  { en: "Father Christmas", cn: "圣诞老人", book: "5A", unit: "8" },
  { en: "next", cn: "接着，然后", book: "5A", unit: "8" },
  { en: "put", cn: "放", book: "5A", unit: "8" },
  { en: "pretty", cn: "漂亮的，好看的", book: "5A", unit: "8" },
  { en: "thing", cn: "物品，东西", book: "5A", unit: "8" },
  { en: "look", cn: "看起来", book: "5A", unit: "8" },
  { en: "Christmas Eve", cn: "圣诞夜，平安夜", book: "5A", unit: "8" },
  { en: "stocking", cn: "长统袜", book: "5A", unit: "8" },
  { en: "wait for", cn: "等候，等待", book: "5A", unit: "8" },
  { en: "finally", cn: "最后", book: "5A", unit: "8" },
  { en: "Christmas Day", cn: "圣诞节", book: "5A", unit: "8" },
  { en: "early", cn: "早早地", book: "5A", unit: "8" },
  { en: "turkey", cn: "火鸡；火鸡肉", book: "5A", unit: "8" },
  { en: "pudding", cn: "布丁", book: "5A", unit: "8" },
  { en: "all", cn: "全都", book: "5A", unit: "8" },
  { en: "have a good time", cn: "过得愉快，玩得高兴", book: "5A", unit: "8" },
  { en: "card", cn: "卡片", book: "5A", unit: "8" },
  { en: "children", cn: "孩子，儿童", book: "5A", unit: "8" },
  { en: "message", cn: "信息；消息", book: "5A", unit: "8" },
  { en: "Merry Christmas!", cn: "圣诞快乐！", book: "5A", unit: "8" },
  { en: "song", cn: "歌曲", book: "5A", unit: "8" },
  { en: "What's wrong with...?", cn: "……怎么了？", book: "5A", unit: "8" },
  { en: "him", cn: "他", book: "5A", unit: "8" },
  { en: "us", cn: "我们", book: "5A", unit: "8" },
  { en: "letter", cn: "信", book: "5A", unit: "8" },
  { en: "storybook", cn: "故事书", book: "5A", unit: "8" },
  { en: "after", cn: "在…以后", book: "5A", unit: "8" },
  { en: "prince", cn: "王子", book: "5B", unit: "1" },
  { en: "fairy", cn: "仙女", book: "5B", unit: "1" },
  { en: "why", cn: "为什么", book: "5B", unit: "1" },
  { en: "because", cn: "因为", book: "5B", unit: "1" },
  { en: "clothes", cn: "衣服", book: "5B", unit: "1" },
  { en: "let", cn: "让", book: "5B", unit: "1" },
  { en: "put on", cn: "穿上", book: "5B", unit: "1" },
  { en: "before", cn: "在…以前", book: "5B", unit: "1" },
  { en: "have to", cn: "不得不，必须", book: "5B", unit: "1" },
  { en: "try on", cn: "试穿", book: "5B", unit: "1" },
  { en: "fit", cn: "合适，合身", book: "5B", unit: "1" },
  { en: "take off", cn: "脱下", book: "5B", unit: "1" },
  { en: "mushroom", cn: "蘑菇", book: "5B", unit: "1" },
  { en: "late", cn: "迟的，晚的", book: "5B", unit: "1" },
  { en: "pick", cn: "摘，拾", book: "5B", unit: "1" },
  { en: "understand", cn: "明白，理解", book: "5B", unit: "1" },
  { en: "be bad for", cn: "有害的", book: "5B", unit: "1" },
  { en: "leave ... behind", cn: "留下，丢下", book: "5B", unit: "1" },
  { en: "far from", cn: "离……远", book: "5B", unit: "2" },
  { en: "near", cn: "在……附近", book: "5B", unit: "2" },
  { en: "by ...", cn: "乘（汽车、火车等）", book: "5B", unit: "2" },
  { en: "bus", cn: "公共汽车，大巴士", book: "5B", unit: "2" },
  { en: "on foot", cn: "步行", book: "5B", unit: "2" },
  { en: "metro", cn: "地铁", book: "5B", unit: "2" },
  { en: "taxi", cn: "出租车，的士", book: "5B", unit: "2" },
  { en: "bike", cn: "自行车", book: "5B", unit: "2" },
  { en: "plane", cn: "飞机", book: "5B", unit: "2" },
  { en: "ship", cn: "轮船", book: "5B", unit: "2" },
  { en: "train", cn: "火车", book: "5B", unit: "2" },
  { en: "ride", cn: "骑车", book: "5B", unit: "2" },
  { en: "show", cn: "给……看", book: "5B", unit: "2" },
  { en: "basket", cn: "篮子", book: "5B", unit: "2" },
  { en: "city", cn: "城市", book: "5B", unit: "2" },
  { en: "ask the way", cn: "问路", book: "5B", unit: "3" },
  { en: "get to", cn: "到达", book: "5B", unit: "3" },
  { en: "take", cn: "搭乘", book: "5B", unit: "3" },
  { en: "get on", cn: "上车", book: "5B", unit: "3" },
  { en: "get off", cn: "下车", book: "5B", unit: "3" },
  { en: "walk", cn: "走，步行", book: "5B", unit: "3" },
  { en: "bookshop", cn: "书店", book: "5B", unit: "3" },
  { en: "street", cn: "街道", book: "5B", unit: "3" },
  { en: "next to", cn: "在……旁边", book: "5B", unit: "3" },
  { en: "See you later.", cn: "一会儿见。", book: "5B", unit: "3" },
  { en: "ask ... for help", cn: "向……求助", book: "5B", unit: "3" },
  { en: "excuse me", cn: "劳驾；对不起", book: "5B", unit: "3" },
  { en: "along", cn: "沿着，顺着", book: "5B", unit: "3" },
  { en: "turn right", cn: "向右转", book: "5B", unit: "3" },
  { en: "traffic light", cn: "交通灯", book: "5B", unit: "3" },
  { en: "on your right", cn: "在你的右侧", book: "5B", unit: "3" },
  { en: "cinema", cn: "电影院", book: "5B", unit: "3" },
  { en: "hospital", cn: "医院", book: "5B", unit: "3" },
  { en: "shop", cn: "商店", book: "5B", unit: "3" },
  { en: "zoo", cn: "动物园", book: "5B", unit: "3" },
  { en: "turn left", cn: "向左转", book: "5B", unit: "3" },
  { en: "supermarket", cn: "超市", book: "5B", unit: "3" },
  { en: "stop", cn: "车站", book: "5B", unit: "3" },
  { en: "full", cn: "满的，饱的", book: "5B", unit: "3" },
  { en: "over", cn: "结束了，完了", book: "5B", unit: "3" },
  { en: "see the doctor", cn: "看医生，看病", book: "5B", unit: "4" },
  { en: "feel", cn: "感觉，感到", book: "5B", unit: "4" },
  { en: "check", cn: "检查", book: "5B", unit: "4" },
  { en: "should", cn: "应该", book: "5B", unit: "4" },
  { en: "have a rest", cn: "休息", book: "5B", unit: "4" },
  { en: "take medicine", cn: "吃药", book: "5B", unit: "4" },
  { en: "drink water", cn: "喝水", book: "5B", unit: "4" },
  { en: "toothache", cn: "牙疼", book: "5B", unit: "4" },
  { en: "dentist", cn: "牙医", book: "5B", unit: "4" },
  { en: "anything", cn: "任何东西", book: "5B", unit: "4" },
  { en: "Brush one's teeth", cn: "刷牙", book: "5B", unit: "4" },
  { en: "bedtime", cn: "就寝时间", book: "5B", unit: "4" },
  { en: "giraffe", cn: "长颈鹿", book: "5B", unit: "4" },
  { en: "point at", cn: "指着，指向", book: "5B", unit: "4" },
  { en: "neck", cn: "脖子", book: "5B", unit: "4" },
  { en: "parent", cn: "父或母", book: "5B", unit: "5" },
  { en: "clean", cn: "擦，洗", book: "5B", unit: "5" },
  { en: "cook", cn: "烧，煮", book: "5B", unit: "5" },
  { en: "sweep the floor", cn: "扫地", book: "5B", unit: "5" },
  { en: "busy", cn: "忙，忙碌", book: "5B", unit: "5" },
  { en: "wash the dishes", cn: "洗碗", book: "5B", unit: "5" },
  { en: "make the bed", cn: "整理床铺", book: "5B", unit: "5" },
  { en: "grow", cn: "种植", book: "5B", unit: "5" },
  { en: "garden", cn: "花园，果园", book: "5B", unit: "5" },
  { en: "sweet", cn: "甜的", book: "5B", unit: "5" },
  { en: "pest", cn: "害虫", book: "5B", unit: "5" },
  { en: "ladybird", cn: "瓢虫", book: "5B", unit: "5" },
  { en: "go away", cn: "走了，走开", book: "5B", unit: "5" },
  { en: "game", cn: "运动，比赛", book: "5B", unit: "6" },
  { en: "smell", cn: "有……气味，闻起来", book: "5B", unit: "6" },
  { en: "meat", cn: "（猪、牛、羊等的）肉", book: "5B", unit: "6" },
  { en: "vegetable", cn: "蔬菜", book: "5B", unit: "6" },
  { en: "tomato", cn: "西红柿，番茄", book: "5B", unit: "6" },
  { en: "potato", cn: "马铃薯，土豆", book: "5B", unit: "6" },
  { en: "I can't wait!", cn: "我等不及了！", book: "5B", unit: "6" },
  { en: "look for", cn: "找，寻找", book: "5B", unit: "6" },
  { en: "ready", cn: "准备好", book: "5B", unit: "6" },
  { en: "yummy", cn: "好吃的，美味的", book: "5B", unit: "6" },
  { en: "love", cn: "喜欢，喜爱", book: "5B", unit: "6" },
  { en: "bread", cn: "面包", book: "5B", unit: "6" },
  { en: "win", cn: "获胜，赢", book: "5B", unit: "6" },
  { en: "yeah", cn: "太好了，太棒了", book: "5B", unit: "6" },
  { en: "angry", cn: "生气的，愤怒的", book: "5B", unit: "6" },
  { en: "spot", cn: "斑，点", book: "5B", unit: "6" },
  { en: "catch", cn: "抓，抓住", book: "5B", unit: "6" },
  { en: "drive ... away", cn: "赶走", book: "5B", unit: "6" },
  { en: "festival", cn: "节日", book: "5B", unit: "7" },
  { en: "Spring Festival", cn: "春节", book: "5B", unit: "7" },
  { en: "January", cn: "一月", book: "5B", unit: "7" },
  { en: "February", cn: "二月", book: "5B", unit: "7" },
  { en: "call", cn: "叫作，称作", book: "5B", unit: "7" },
  { en: "Chinese New Year", cn: "中国农历新年", book: "5B", unit: "7" },
  { en: "get together", cn: "团聚", book: "5B", unit: "7" },
  { en: "dumpling", cn: "饺子", book: "5B", unit: "7" },
  { en: "Dragon Boat Festival", cn: "端午节", book: "5B", unit: "7" },
  { en: "May", cn: "五月", book: "5B", unit: "7" },
  { en: "June", cn: "六月", book: "5B", unit: "7" },
  { en: "dragon boat race", cn: "赛龙舟", book: "5B", unit: "7" },
  { en: "place", cn: "地方，地点", book: "5B", unit: "7" },
  { en: "rice dumpling", cn: "粽子", book: "5B", unit: "7" },
  { en: "Mid-Autumn Festival", cn: "中秋节", book: "5B", unit: "7" },
  { en: "September", cn: "九月", book: "5B", unit: "7" },
  { en: "October", cn: "十月", book: "5B", unit: "7" },
  { en: "moon", cn: "月亮", book: "5B", unit: "7" },
  { en: "moon cake", cn: "月饼", book: "5B", unit: "7" },
  { en: "Double Ninth Festival", cn: "重阳节", book: "5B", unit: "7" },
  { en: "November", cn: "十一月", book: "5B", unit: "7" },
  { en: "old", cn: "老的，年纪大的", book: "5B", unit: "7" },
  { en: "mountain", cn: "山，山脉", book: "5B", unit: "7" },
  { en: "rice cake", cn: "重阳糕", book: "5B", unit: "7" },
  { en: "Mother's Day", cn: "母亲节", book: "5B", unit: "7" },
  { en: "Father's Day", cn: "父亲节", book: "5B", unit: "7" },
  { en: "birthday", cn: "生日", book: "5B", unit: "8" },
  { en: "eleventh", cn: "第十一", book: "5B", unit: "8" },
  { en: "together", cn: "一起", book: "5B", unit: "8" },
  { en: "eighth", cn: "第八", book: "5B", unit: "8" },
  { en: "April", cn: "四月", book: "5B", unit: "8" },
  { en: "go shopping", cn: "去购物", book: "5B", unit: "8" },
  { en: "March", cn: "三月", book: "5B", unit: "8" },
  { en: "July", cn: "七月", book: "5B", unit: "8" },
  { en: "August", cn: "八月", book: "5B", unit: "8" },
  { en: "December", cn: "十二月", book: "5B", unit: "8" },
  { en: "hero", cn: "英雄", book: "5B", unit: "8" },
  { en: "play", cn: "戏，戏剧", book: "5B", unit: "8" },
  { en: "number", cn: "数字，数", book: "5B", unit: "8" },
  { en: "password", cn: "密码", book: "5B", unit: "8" },
  { en: "answer", cn: "答案", book: "5B", unit: "8" },
  { en: "fourth", cn: "第四", book: "5B", unit: "8" },
  { en: "start", cn: "开始", book: "5B", unit: "8" },
  { en: "fight", cn: "打仗，打架", book: "5B", unit: "8" },
  { en: "long long ago", cn: "很久以前", book: "6A", unit: "1" },
  { en: "magic", cn: "有魔力的，神奇的", book: "6A", unit: "1" },
  { en: "clever", cn: "聪明的", book: "6A", unit: "1" },
  { en: "foolish", cn: "愚蠢的", book: "6A", unit: "1" },
  { en: "through", cn: "穿过", book: "6A", unit: "1" },
  { en: "laugh", cn: "笑，大笑", book: "6A", unit: "1" },
  { en: "wear", cn: "穿", book: "6A", unit: "1" },
  { en: "turn into", cn: "变成", book: "6A", unit: "1" },
  { en: "sentence", cn: "句子", book: "6A", unit: "1" },
  { en: "each", cn: "每个", book: "6A", unit: "1" },
  { en: "quick", cn: "迅速的，快的", book: "6A", unit: "1" },
  { en: "think", cn: "想，思考", book: "6A", unit: "1" },
  { en: "another", cn: "又一个", book: "6A", unit: "1" },
  { en: "next", cn: "下一个", book: "6A", unit: "1" },
  { en: "turn", cn: "机会", book: "6A", unit: "1" },
  { en: "hard", cn: "努力地，费劲地", book: "6A", unit: "1" },
  { en: "sunny", cn: "晴朗的", book: "6A", unit: "2" },
  { en: "show", cn: "展览，展示", book: "6A", unit: "2" },
  { en: "interesting", cn: "有趣的，有意思的", book: "6A", unit: "2" },
  { en: "weather", cn: "天气", book: "6A", unit: "2" },
  { en: "become", cn: "变成，变为", book: "6A", unit: "2" },
  { en: "windy", cn: "有风的", book: "6A", unit: "2" },
  { en: "cloudy", cn: "多云的", book: "6A", unit: "2" },
  { en: "high", cn: "在高处", book: "6A", unit: "2" },
  { en: "honey", cn: "蜂蜜", book: "6A", unit: "2" },
  { en: "drink", cn: "饮料", book: "6A", unit: "2" },
  { en: "ant", cn: "蚂蚁", book: "6A", unit: "2" },
  { en: "bee", cn: "蜜蜂", book: "6A", unit: "2" },
  { en: "cloud", cn: "云", book: "6A", unit: "2" },
  { en: "rain", cn: "下雨", book: "6A", unit: "2" },
  { en: "meet", cn: "遇见", book: "6A", unit: "2" },
  { en: "lose", cn: "丢失", book: "6A", unit: "2" },
  { en: "know", cn: "知道", book: "6A", unit: "2" },
  { en: "what happened?", cn: "出什么事了？", book: "6A", unit: "2" },
  { en: "climb up", cn: "爬上", book: "6A", unit: "2" },
  { en: "hold onto", cn: "抓紧", book: "6A", unit: "2" },
  { en: "fly away", cn: "飞走", book: "6A", unit: "2" },
  { en: "holiday", cn: "假日，假期", book: "6A", unit: "3" },
  { en: "National Day", cn: "国庆节", book: "6A", unit: "3" },
  { en: "call", cn: "打电话", book: "6A", unit: "3" },
  { en: "bund", cn: "（上海）外滩", book: "6A", unit: "3" },
  { en: "Shanghai Museum", cn: "上海博物馆", book: "6A", unit: "3" },
  { en: "Great Wall", cn: "长城", book: "6A", unit: "3" },
  { en: "Palace Museum", cn: "故宫", book: "6A", unit: "3" },
  { en: "Summer Palace", cn: "颐和园", book: "6A", unit: "3" },
  { en: "Tian'anmen Square", cn: "天安门广场", book: "6A", unit: "3" },
  { en: "fashion show", cn: "时装表演，时装秀", book: "6A", unit: "3" },
  { en: "bottle", cn: "瓶子", book: "6A", unit: "3" },
  { en: "go well", cn: "进展顺利", book: "6A", unit: "3" },
  { en: "at first", cn: "开始，最初", book: "6A", unit: "3" },
  { en: "heavy rain", cn: "大雨", book: "6A", unit: "3" },
  { en: "then and now", cn: "过去和现在", book: "6A", unit: "4" },
  { en: "ago", cn: "…以前", book: "6A", unit: "4" },
  { en: "telephone", cn: "电话", book: "6A", unit: "4" },
  { en: "office", cn: "办公室", book: "6A", unit: "4" },
  { en: "mobile phone", cn: "移动电话", book: "6A", unit: "4" },
  { en: "any where", cn: "随处，到处", book: "6A", unit: "4" },
  { en: "radio", cn: "收音机", book: "6A", unit: "4" },
  { en: "newspaper", cn: "报纸", book: "6A", unit: "4" },
  { en: "news", cn: "新闻", book: "6A", unit: "4" },
  { en: "e-book", cn: "电子书", book: "6A", unit: "4" },
  { en: "make friends", cn: "交朋友", book: "6A", unit: "4" },
  { en: "all over the world", cn: "全世界", book: "6A", unit: "4" },
  { en: "do shopping", cn: "购物", book: "6A", unit: "4" },
  { en: "TV", cn: "电视", book: "6A", unit: "4" },
  { en: "look out of", cn: "朝……外看", book: "6A", unit: "4" },
  { en: "What day is today?", cn: "今天是星期几？", book: "6A", unit: "4" },
  { en: "go on", cn: "继续", book: "6A", unit: "4" },
  { en: "spell", cn: "拼读，拼写", book: "6A", unit: "4" },
  { en: "make a sentence", cn: "造句", book: "6A", unit: "4" },
  { en: "with", cn: "用", book: "6A", unit: "4" },
  { en: "yesterday", cn: "昨天", book: "6A", unit: "4" },
  { en: "sign", cn: "标识", book: "6A", unit: "5" },
  { en: "shopping center", cn: "购物中心", book: "6A", unit: "5" },
  { en: "careful", cn: "小心，当心", book: "6A", unit: "5" },
  { en: "What does it mean?", cn: "这是什么意思？", book: "6A", unit: "5" },
  { en: "mean", cn: "意思是", book: "6A", unit: "5" },
  { en: "litter", cn: "乱扔垃圾", book: "6A", unit: "5" },
  { en: "go in", cn: "进入", book: "6A", unit: "5" },
  { en: "take", cn: "携带", book: "6A", unit: "5" },
  { en: "restaurant", cn: "饭店，餐厅", book: "6A", unit: "5" },
  { en: "someone", cn: "某人", book: "6A", unit: "5" },
  { en: "smell", cn: "闻到", book: "6A", unit: "5" },
  { en: "No eating or drinking.", cn: "请勿饮食。", book: "6A", unit: "5" },
  { en: "No littering.", cn: "请勿乱扔垃圾。", book: "6A", unit: "5" },
  { en: "No parking.", cn: "请勿停车。", book: "6A", unit: "5" },
  { en: "No smoking.", cn: "请勿抽烟。", book: "6A", unit: "5" },
  { en: "Danger！", cn: "危险！", book: "6A", unit: "5" },
  { en: "Wet floor.", cn: "小心地滑.", book: "6A", unit: "5" },
  { en: "outing", cn: "外出游玩，远足", book: "6A", unit: "5" },
  { en: "walk on", cn: "继续走路", book: "6A", unit: "5" },
  { en: "around", cn: "在……周围", book: "6A", unit: "5" },
  { en: "keep", cn: "保持，维持", book: "6A", unit: "6" },
  { en: "clean", cn: "干净的，整洁的", book: "6A", unit: "6" },
  { en: "make", cn: "使……变得", book: "6A", unit: "6" },
  { en: "photo", cn: "照片", book: "6A", unit: "6" },
  { en: "air", cn: "空气", book: "6A", unit: "6" },
  { en: "dirty", cn: "肮脏的", book: "6A", unit: "6" },
  { en: "smoke", cn: "烟雾", book: "6A", unit: "6" },
  { en: "rubbish", cn: "垃圾", book: "6A", unit: "6" },
  { en: "messy", cn: "肮脏的，乱七八糟的", book: "6A", unit: "6" },
  { en: "dead", cn: "死的", book: "6A", unit: "6" },
  { en: "move ... away from", cn: "从……搬走", book: "6A", unit: "6" },
  { en: "bin", cn: "垃圾桶", book: "6A", unit: "6" },
  { en: "plant", cn: "种植，栽种", book: "6A", unit: "6" },
  { en: "more", cn: "更多的", book: "6A", unit: "6" },
  { en: "museum", cn: "博物馆", book: "6A", unit: "6" },
  { en: "throw", cn: "扔", book: "6A", unit: "6" },
  { en: "skin", cn: "果皮", book: "6A", unit: "6" },
  { en: "pick ... up", cn: "捡起，拾起", book: "6A", unit: "6" },
  { en: "slip", cn: "滑倒", book: "6A", unit: "6" },
  { en: "fall", cn: "摔倒", book: "6A", unit: "6" },
  { en: "protect", cn: "保护", book: "6A", unit: "7" },
  { en: "Earth", cn: "地球", book: "6A", unit: "7" },
  { en: "save", cn: "节约", book: "6A", unit: "7" },
  { en: "useful", cn: "有用的", book: "6A", unit: "7" },
  { en: "use", cn: "使用，利用", book: "6A", unit: "7" },
  { en: "waste", cn: "浪费", book: "6A", unit: "7" },
  { en: "much", cn: "很多", book: "6A", unit: "7" },
  { en: "reuse", cn: "再利用", book: "6A", unit: "7" },
  { en: "energy", cn: "能源", book: "6A", unit: "7" },
  { en: "come from", cn: "从……来，来自", book: "6A", unit: "7" },
  { en: "coal", cn: "煤炭", book: "6A", unit: "7" },
  { en: "oil", cn: "石油", book: "6A", unit: "7" },
  { en: "drive", cn: "开车，驾车", book: "6A", unit: "7" },
  { en: "wood", cn: "木头，木材", book: "6A", unit: "7" },
  { en: "cut down", cn: "砍伐，砍掉", book: "6A", unit: "7" },
  { en: "too many", cn: "太多", book: "6A", unit: "7" },
  { en: "plastic", cn: "塑料", book: "6A", unit: "7" },
  { en: "paper", cn: "纸", book: "6A", unit: "7" },
  { en: "glass", cn: "玻璃", book: "6A", unit: "7" },
  { en: "project", cn: "课题", book: "6A", unit: "7" },
  { en: "poster", cn: "海报", book: "6A", unit: "7" },
  { en: "gate", cn: "大门", book: "6A", unit: "7" },
  { en: "Hong Kong", cn: "香港", book: "6A", unit: "8" },
  { en: "excited", cn: "激动的，兴奋的", book: "6A", unit: "8" },
  { en: "food", cn: "食物，食品", book: "6A", unit: "8" },
  { en: "tangyuan", cn: "汤圆", book: "6A", unit: "8" },
  { en: "Chinese New Year's Eve", cn: "大年夜，除夕", book: "6A", unit: "8" },
  { en: "Chinese New Year's Day", cn: "大年初一，春节", book: "6A", unit: "8" },
  { en: "red packet", cn: "红包", book: "6A", unit: "8" },
  { en: "lion dance", cn: "舞狮", book: "6A", unit: "8" },
  { en: "fireworks", cn: "烟花表演", book: "6A", unit: "8" },
  { en: "firecracker", cn: "鞭炮", book: "6A", unit: "8" },
  { en: "rich", cn: "富有的，有钱的", book: "6A", unit: "8" },
  { en: "plan", cn: "计划，打算", book: "6A", unit: "8" },
  { en: "hooray", cn: "好极了", book: "6A", unit: "8" },
  { en: "mouse", cn: "老鼠", book: "6B", unit: "1" },
  { en: "large", cn: "大的", book: "6B", unit: "1" },
  { en: "strong", cn: "强大的，强壮的", book: "6B", unit: "1" },
  { en: "walk by", cn: "走过，路过", book: "6B", unit: "1" },
  { en: "wake ... up", cn: "吵醒，叫醒", book: "6B", unit: "1" },
  { en: "some day", cn: "某一天", book: "6B", unit: "1" },
  { en: "quietly", cn: "小声地，安静地", book: "6B", unit: "1" },
  { en: "loudly", cn: "大声地", book: "6B", unit: "1" },
  { en: "the next day", cn: "第二天", book: "6B", unit: "1" },
  { en: "net", cn: "网", book: "6B", unit: "1" },
  { en: "bite", cn: "咬", book: "6B", unit: "1" },
  { en: "sharp", cn: "锋利的，尖的", book: "6B", unit: "1" },
  { en: "ask", cn: "问", book: "6B", unit: "1" },
  { en: "just then", cn: "就在那时", book: "6B", unit: "1" },
  { en: "soon", cn: "不久，很快", book: "6B", unit: "1" },
  { en: "get out", cn: "出来，出去", book: "6B", unit: "1" },
  { en: "happily", cn: "开心地，高兴地", book: "6B", unit: "1" },
  { en: "from then on", cn: "从那时起", book: "6B", unit: "1" },
  { en: "weak", cn: "弱的，软弱的", book: "6B", unit: "1" },
  { en: "cheer", cn: "欢呼", book: "6B", unit: "1" },
  { en: "hit", cn: "打，击", book: "6B", unit: "1" },
  { en: "ground", cn: "地面，地上", book: "6B", unit: "1" },
  { en: "deep", cn: "深的", book: "6B", unit: "1" },
  { en: "reach", cn: "够得着", book: "6B", unit: "1" },
  { en: "pour ... into", cn: "把……倒入", book: "6B", unit: "1" },
  { en: "child", cn: "孩子，小孩", book: "6B", unit: "2" },
  { en: "habit", cn: "习惯", book: "6B", unit: "2" },
  { en: "never", cn: "从不", book: "6B", unit: "2" },
  { en: "late", cn: "迟，晚", book: "6B", unit: "2" },
  { en: "put ... in order", cn: "把……整理得井井有条", book: "6B", unit: "2" },
  { en: "finish", cn: "完成", book: "6B", unit: "2" },
  { en: "tidy", cn: "干净的，整齐的", book: "6B", unit: "2" },
  { en: "bad", cn: "不好的，坏的", book: "6B", unit: "2" },
  { en: "sleepy", cn: "困的，困倦的", book: "6B", unit: "2" },
  { en: "last night", cn: "昨夜", book: "6B", unit: "2" },
  { en: "fast", cn: "快地", book: "6B", unit: "2" },
  { en: "go into", cn: "走进，走入", book: "6B", unit: "2" },
  { en: "healthy", cn: "健康的", book: "6B", unit: "3" },
  { en: "diet", cn: "饮食", book: "6B", unit: "3" },
  { en: "a little", cn: "一点", book: "6B", unit: "3" },
  { en: "a few", cn: "几个", book: "6B", unit: "3" },
  { en: "at a time", cn: "一次", book: "6B", unit: "3" },
  { en: "cola", cn: "可乐", book: "6B", unit: "3" },
  { en: "too much", cn: "太多", book: "6B", unit: "3" },
  { en: "need", cn: "需要", book: "6B", unit: "3" },
  { en: "road", cn: "马路，公路", book: "6B", unit: "4" },
  { en: "safety", cn: "安全", book: "6B", unit: "4" },
  { en: "cross", cn: "穿过，穿行", book: "6B", unit: "4" },
  { en: "safely", cn: "安全地", book: "6B", unit: "4" },
  { en: "must", cn: "必须", book: "6B", unit: "4" },
  { en: "zebra crossing", cn: "斑马线", book: "6B", unit: "4" },
  { en: "safe", cn: "安全的", book: "6B", unit: "4" },
  { en: "pavement", cn: "人行道", book: "6B", unit: "4" },
  { en: "look out for", cn: "当心，提防", book: "6B", unit: "4" },
  { en: "follow", cn: "遵守", book: "6B", unit: "4" },
  { en: "rule", cn: "规则", book: "6B", unit: "4" },
  { en: "stay", cn: "保持", book: "6B", unit: "4" },
  { en: "light", cn: "灯", book: "6B", unit: "4" },
  { en: "Children's Day", cn: "儿童节", book: "6B", unit: "5" },
  { en: "clown", cn: "小丑", book: "6B", unit: "5" },
  { en: "balloon", cn: "气球", book: "6B", unit: "5" },
  { en: "appear", cn: "出现", book: "6B", unit: "5" },
  { en: "begin", cn: "开始", book: "6B", unit: "5" },
  { en: "put on", cn: "上演，表演", book: "6B", unit: "5" },
  { en: "country", cn: "国家", book: "6B", unit: "6" },
  { en: "learn", cn: "学习", book: "6B", unit: "6" },
  { en: "about", cn: "关于", book: "6B", unit: "6" },
  { en: "next week", cn: "下周", book: "6B", unit: "6" },
  { en: "find out", cn: "发现", book: "6B", unit: "6" },
  { en: "magazine", cn: "杂志", book: "6B", unit: "6" },
  { en: "kangaroo", cn: "袋鼠", book: "6B", unit: "6" },
  { en: "koala", cn: "考拉", book: "6B", unit: "6" },
  { en: "lover", cn: "爱好者", book: "6B", unit: "6" },
  { en: "Australian football", cn: "澳式橄榄球", book: "6B", unit: "6" },
  { en: "exciting", cn: "令人激动的，令人兴奋的", book: "6B", unit: "6" },
  { en: "Sydney", cn: "（澳大利亚城市）悉尼", book: "6B", unit: "6" },
  { en: "welcome", cn: "欢迎", book: "6B", unit: "6" },
  { en: "visitor", cn: "游人，游客", book: "6B", unit: "6" },
  { en: "London", cn: "（英国城市）伦敦", book: "6B", unit: "6" },
  { en: "Oxford", cn: "（英国城市）牛津", book: "6B", unit: "6" },
  { en: "Big Ben", cn: "（英国）大本钟", book: "6B", unit: "6" },
  { en: "London Eye", cn: "（伦敦的摩天轮）伦敦眼", book: "6B", unit: "6" },
  { en: "Tower Bridge", cn: "（伦敦）塔桥", book: "6B", unit: "6" },
  { en: "like", cn: "如", book: "6B", unit: "6" },
  { en: "What do you think?", cn: "你觉得呢?", book: "6B", unit: "6" },
  { en: "summer holiday", cn: "暑假", book: "6B", unit: "7" },
  { en: "will", cn: "将，将要", book: "6B", unit: "7" },
  { en: "go back to", cn: "回去", book: "6B", unit: "7" },
  { en: "how long", cn: "多久", book: "6B", unit: "7" },
  { en: "stay", cn: "停留", book: "6B", unit: "7" },
  { en: "sound", cn: "听起来，听上去", book: "6B", unit: "7" },
  { en: "Disneyland", cn: "迪士尼乐园", book: "6B", unit: "7" },
  { en: "Ocean Park", cn: "（香港）海洋公园", book: "6B", unit: "7" },
  { en: "Taipei", cn: "台北", book: "6B", unit: "7" },
  { en: "travel", cn: "旅游", book: "6B", unit: "7" },
  { en: "traveller", cn: "旅行者", book: "6B", unit: "7" },
  { en: "travel around the world", cn: "环游世界", book: "6B", unit: "7" },
  { en: "dream", cn: "梦想", book: "6B", unit: "8" },
  { en: "future", cn: "将来，未来", book: "6B", unit: "8" },
  { en: "care about", cn: "关心，在乎", book: "6B", unit: "8" },
  { en: "astronaut", cn: "宇航员", book: "6B", unit: "8" },
  { en: "spaceship", cn: "宇宙飞船", book: "6B", unit: "8" },
  { en: "Moon", cn: "月球", book: "6B", unit: "8" },
  { en: "football player", cn: "足球运动员", book: "6B", unit: "8" },
  { en: "World Cup", cn: "世界杯", book: "6B", unit: "8" },
  { en: "dancer", cn: "舞蹈家", book: "6B", unit: "8" },
  { en: "pianist", cn: "钢琴演奏家", book: "6B", unit: "8" },
  { en: "come true", cn: "实现，成真", book: "6B", unit: "8" },
  { en: "take care of", cn: "爱护；照顾", book: "6B", unit: "8" },
  { en: "scientist", cn: "科学家", book: "6B", unit: "8" },
  { en: "artist", cn: "艺术家", book: "6B", unit: "8" },
  { en: "paint", cn: "画画", book: "6B", unit: "8" },
];
